name: Setup workspace
description: This action is used to setup workspace for running tests and publishing packages.
inputs:
  node-version:
    required: true
    description: Node Version to setup

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/setup@v1
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true

    - name: Setup pnpm
      shell: bash
      run: npm i -g pnpm

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
