name: Setup workspace
description: This action is used to setup workspace for running tests and publishing packages.
inputs:
  node-version:
    required: true
    description: Node Version to setup

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/setup@v1
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true

    - name: Setup pnpm
      shell: bash
      run: npm i -g pnpm

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile

    - name: Store Playwright's Version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm list playwright | grep playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-v1-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-playwright-v1-${{ env.PLAYWRIGHT_VERSION }}
          ${{ runner.os }}-playwright-v1-
