module.exports = {
  fileHeader: '# THIS FILE WAS AUTOGENERATED BY SIFRR-API. DO NOT EDIT THIS FILE DIRECTLY.\n',
  timestampHeader: `# Genarated at ${new Date().toUTCString()} (${Date.now()})\n`,
  fileSeparator: '#### Graphql Schema ####\n\n'
};
