module.exports = {
  fileHeader: '# THIS FILE WAS AUTOGENERATED BY SIFRR-API. DO NOT EDIT THIS FILE DIRECTLY.\n',
  timestampHeader: date => `# Genarated at ${date.toUTCString()} (${date.getTime()})\n`,
  fileSeparator: '#### Graphql Schema ####\n\n'
};
