#!/usr/bin/env node

const package = require('../../package.json');
const fs = require('fs');
let packageFileString = '../.' + process.argv[2], packageFile;
let temp = process.argv[2].split('/')
let jsFileName = temp[temp.length - 2].replace('-', '.')
let packageName = '@' + jsFileName.replace('.', '/')
let packageToMerge = {
  "name": packageName,
  "main": `src/${jsFileName}.js`,
  "browser": `dist/${jsFileName}.js`,
  "version": package.version,
  "licence": package.licence,
  "browserslist": package.browserslist,
  "repository": package.repository,
  "author": package.author,
  "bugs": package.bugs,
  "homepage": package.homepage
}

try {
  packageFile  = require(packageFileString);
} catch(e) {
  console.log('No package file in this folder');
  process.exit(0);
}

Object.assign(packageFile, packageToMerge);
fs.writeFileSync(__dirname + '/' + packageFileString, JSON.stringify(packageFile, null, 2) + '\n');
console.log("Done");
