#!/usr/bin/env node

const version = require('../../package.json').version;
const exec = require('../exec');
const tag = 'v' + version;

(async function() {
  await exec(`git tag -a ${tag} -m "Release of ${tag}"`);
  process.stdout.write('---------');
  await exec(`git push origin ${tag}`);
})();
