#!/usr/bin/env node

const version = require('../../package.json').version;
const exec = require('../exec');
const tag = 'v' + version;

(async function() {
  await exec('git pull');
  exec(`git rev-parse ${tag}^{tag}`).then(() => {
    process.stdout.write(`Tag ${tag} already exists.`);
  }).catch(async () => {
    await exec(`git tag -a ${tag} -m "Release of ${tag}"`);
    process.stdout.write('---------');
    await exec(`git push origin ${tag}`);
  });
})();
