#!/usr/bin/env node

const path = require('path');
const { loadDir, generateChangelog } = require('@sifrr/dev');

loadDir({
  dir: path.resolve('./packages'),
  onDir: (dir) => {
    if (dir.match(/sifrr-[a-z]*/)) {
      generateChangelog({
        changelogFile: path.join(dir, './CHANGELOG.md'),
        multiRepo: path.basename(dir)
      });
    }
  },
  deep: 1
});

generateChangelog();
