#!/usr/bin/env node

const path = require('path');
const { loadDir, generateChangelog } = require('@sifrr/dev');

loadDir({
  dir: path.resolve('./elements'),
  onDir: (dir) => {
    generateChangelog({
      changelogFile: path.join(dir, './CHANGELOG.md'),
      multiRepo: path.basename(dir)
    });
  },
  deep: 0
});

generateChangelog();
