#!/usr/bin/env bash

set -ex

./scripts/release/config
./scripts/yarn build
./scripts/release/tag
./scripts/repeat "./packages/browser/*" "npm publish --access=public"
./scripts/repeat "./packages/server/*" "npm publish --access=public"
