#!/usr/bin/env bash

DIRS="${1%\"}"
DIRS="${DIRS#\"}"

COMMAND="${2%\"}"
COMMAND="${COMMAND#\"}"

for dir in $DIRS
do
  cd "$dir"
  echo "Running $COMMAND in $PWD"
  $COMMAND "${@:3}"
  cd "$OLDPWD"
done
