#!/usr/bin/env bash

STATUS=0

if [[ $COVERAGE == 'true' ]]; then
  find ./.nyc_output -name "*coverage*.json" -delete
  rm -rf ./.nyc_output/js
fi

dirs=""

for dir in ./packages/*/*
do
  dirs="$dirs,$dir"
done

echo "Running test in ${dirs}:"
./scripts/test/run "${dirs}" "$@"

NEW_STATUS=$?
[ $NEW_STATUS -eq 0 ] || STATUS=1
exit $STATUS # Exit with 1 if any test failed
