#!/usr/bin/env bash

set -x

STATUS=0

if [[ $COVERAGE == 'true' ]]; then
  rm -rf ./.nyc_output
fi

dirs=(./packages/*/*)
dirsc=$(echo "${dirs[@]}")
node ./scripts/test/run.js "${dirsc}" "$@"

NEW_STATUS=$?
[ $NEW_STATUS -eq 0 ] || STATUS=$NEW_STATUS

if [[ $COVERAGE == 'true' ]]; then
  if [[ $LCOV == 'true' ]]; then
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  fi
fi

exit $STATUS # Exit with 1 if any test failed
