#!/usr/bin/env bash

set -x

STATUS=0

if [[ $COVERAGE == 'true' ]]; then
  rm -rf ./.nyc_output
fi

if [ -z ${CIRCLE_NODE_TOTAL} ]; then
  FOLDERS="./packages/*/*"
else
  FOLDERS=`circleci tests glob "packages/*/*" | circleci tests split --split-by=timings`
fi

for dir in $FOLDERS
do
  echo "Running test in ${dir}:"
  node ./scripts/test/run.js "${dir}" "$@"

  NEW_STATUS=$?
  [ $NEW_STATUS -eq 0 ] || STATUS=$NEW_STATUS
done

if [[ $COVERAGE == 'true' ]]; then
  node ./scripts/test/htmlcoverage.js
  if [[ $LCOV == 'true' ]]; then
    COVERALLS_REPO_TOKEN=hBmgJrJrMMh6yjpePxajlVNzOh8WM3QpA cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  fi
fi

exit $STATUS # Exit with 1 if any test failed
