#!/usr/bin/env bash

set -x

STATUS=0

if [[ $COVERAGE == 'true' ]]; then
  rm -rf ./.nyc_output
fi

for dir in ./packages/*/*
do
  echo "Running test in ${dir}:"
  node ./scripts/test/run.js "${dir}" "$@"

  NEW_STATUS=$?
  [ $NEW_STATUS -eq 0 ] || STATUS=$NEW_STATUS
done

if [[ $COVERAGE == 'true' ]]; then
  if [[ $LCOV == 'true' ]]; then
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  fi
fi

exit $STATUS # Exit with 1 if any test failed
