name: Release Stable Packages

on:
  workflow_dispatch:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'release') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Workspace
        uses: ./.github/actions/setup
        with:
          node-version: 20.x

      - name: Release packages
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN_WEB }}

      - name: Push tags
        if: always()
        run: |
          git fetch --tags
          ./scripts/createTags
          git push origin --tags
